server:
  host: localhost
  port: 8095
  context-path: /gestao

helianto:
  host: localhost
  db-host: localhost
  port: 8081
  title: Gestão Brasil
  base-name: gestao
  api:
    url: http://${helianto.host}:${helianto.port}
  partner:
    host: ${helianto.host}
    port: 8095

spring:
  profiles:
    active: test
  freemarker:
    template-loader-path: classpath:/templates/, /templates/
    prefer-file-system-access: false

http:
  multipart:
    max-file-size: 12MB
    max-request-size: 12MB

security:
  oauth2:
    client:
      client-id: iservport-trusted-client
      scope: read,write
      authorized-grant-types: authorization_code
      accessTokenUri: http://${helianto.host}:${helianto.port}/oauth/token
      userAuthorizationUri: http://${helianto.host}:${helianto.port}/oauth/authorize
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApUzN1WkOas3R8908zqos
          WPqfZW0JEXqApe9/jRBQM2sCmdoRSTTeF53OQeDfBpKNYjeVk2WDVd694Mil2yuZ
          jhqvkRbV51OndCq41Zve45HHNK63mdwd7s0QpPrL0m/QAn3XkduLIW/NlVkR6oQX
          k4EHNx+8AjBPbEVyIPpr71549isjECyI9Nh2rooR+g9pEk/U52YGtW1PjYBT9NRJ
          MatpqJ7dv02Iu5sF32wopHGe/rCgFX2XdHrWRCjpX0gkeNtD0QK5JRMLerySlF0c
          kcI3PnDDFLhGGxxylT9FaYEW50HYnHaBIKQfXcBpf8yHka3wkeR+t1Wrpu3vcIhT
          mQIDAQAB
          -----END PUBLIC KEY-----

logging:
  level:
    org.springframework.security: off
    com.iservport.gestao: DEBUG
    org.hibernate: off
    org.hibernate.SQL: DEBUG
    com.fasterxml.jackson: DEBUG

